boring.words = c(
  "^[0123456789]+",
  "fashion week",
  "bank of",
  " alert ",
  "daily",
  "^morning",
  "podcast",
  "popcast",
  "book review",
  "britain",
  "british",
  "first draft",
  "live coverage",
  "a photog",
  "activisist",
  "whats going",
  "what were",
  "weekly news",
  "weekly wrap",
  "weekend reading",
  "^what are",
  "^(chinese|china)",
  "classical",
  "today in",
  "^from",
  "gotham",
  "hong kong",
  "inside the",
  " arts ",
  "of the day",
  "politics",
  "preparing",
  "^obama",
  "^on this",
  "^on the",
  "^outside",
  "of the day",
  "poet",
  "throwback",
  "toronto",
  "^tune in",
  "verbatim",
  "video review",
  "watch now",
  "in performance",
  "ZZZZZ"
)

######
#
######
## boring.words = c(
##   "toronto", 
##   "^reading the times",
##   "^new ", #?
##   "^former",
##   "hong kong",
##   "^behind",
##   "^first draft",
##   "^book review",
##   "beijing", 
##   "^china",
##   "^chinese",
##   "in china",
##   "^classical",
##   "^daily",
##   "^friday night",
##   "^[0123456789]",
##   "^british",
##   "^from the upshot",
##   "^europ",
##   "^first draft",
##   "in performance",
##   "fashion week",
##   "pictures of the day",
##   "the week ahead$",
##   "money talking$",
##   "^lunchtime laughs",
##   "^morning agenda",
##   "^today in",
##   "^new york today",
##   "^NYTL|^obama",
##   "^on this day",
##   "^q and a",
##   "top 10",
##   "^test yourself",
##   "the daily gift",
##   "^throwback thursday",
##   "tune in to the times",
##   "^verbatim",
##   "^video reviews",
##   "^walkabout",
##   "^weekly (wrap|news)",
##   "^what we're (reading|watching)",
##   "^what's going on",
##   "white house",
##   "word of the day",
##   "^what were",
##   "^whats going on in",
##   "ZZZZZZZZZ"
## )
